name: Build and test Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go run ron.go build linux

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test
